const menuToggle=document.querySelector('[data-menu-toggle]');
const siteNav=document.querySelector('[data-site-nav]');
const reveals=document.querySelectorAll('.reveal');
const enterBtn=document.querySelector('[data-enter-site]');
const welcome=document.querySelector('[data-welcome]');
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let globalPointer={x:window.innerWidth*.5,y:window.innerHeight*.45,active:false};
function setPointerVars(x,y){globalPointer={x,y,active:true};document.documentElement.style.setProperty('--mx',`${x}px`);document.documentElement.style.setProperty('--my',`${y}px`)}
setPointerVars(globalPointer.x,globalPointer.y);
window.addEventListener('pointermove',e=>setPointerVars(e.clientX,e.clientY),{passive:true});
window.addEventListener('scroll',()=>{document.documentElement.style.setProperty('--scrollY',`${window.scrollY}px`)},{passive:true});
menuToggle?.addEventListener('click',()=>{const open=siteNav?.classList.toggle('is-open');menuToggle.setAttribute('aria-expanded',String(Boolean(open))) });
if(enterBtn&&welcome){document.body.classList.add('no-scroll');enterBtn.addEventListener('click',()=>{welcome.classList.add('is-hidden');document.body.classList.remove('no-scroll')});}
const observer='IntersectionObserver'in window?new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}})},{threshold:.1,rootMargin:'0px 0px -30px 0px'}):null;
reveals.forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i*35,210)}ms`;observer?observer.observe(el):el.classList.add('in-view')});
document.querySelectorAll('[data-sound-control]').forEach(control=>{const audio=control.querySelector('[data-audio]');const btn=control.querySelector('[data-sound-toggle]');const label=control.querySelector('[data-sound-label]');if(!audio||!btn||!label)return;const sync=playing=>{btn.classList.toggle('is-playing',playing);btn.setAttribute('aria-pressed',String(playing));label.textContent=playing?'Pause':'Play me'};btn.addEventListener('click',async()=>{try{document.querySelectorAll('[data-audio]').forEach(a=>{if(a!==audio)a.pause()});document.querySelectorAll('[data-sound-toggle]').forEach(b=>{if(b!==btn)b.classList.remove('is-playing')});if(audio.paused){await audio.play();sync(true)}else{audio.pause();sync(false)}}catch(e){label.textContent='Tap again'}});audio.addEventListener('ended',()=>sync(false));audio.addEventListener('pause',()=>{if(!audio.ended)sync(false)})});
const locationPins=document.querySelectorAll('[data-location-pin]');const locationTitle=document.querySelector('[data-location-title]');const locationCopy=document.querySelector('[data-location-copy]');locationPins.forEach(pin=>pin.addEventListener('click',()=>{locationPins.forEach(p=>p.classList.remove('is-active'));pin.classList.add('is-active');if(locationTitle)locationTitle.textContent=pin.dataset.title||'Metro Manila';if(locationCopy)locationCopy.textContent=pin.dataset.copy||''}));locationPins[0]?.classList.add('is-active');
const dialog=document.querySelector('[data-product-dialog]');const dialogTitle=document.querySelector('[data-dialog-title]');const dialogCopy=document.querySelector('[data-dialog-copy]');const dialogBest=document.querySelector('[data-dialog-best]');const dialogTip=document.querySelector('[data-dialog-tip]');const dialogStorage=document.querySelector('[data-dialog-storage]');document.querySelectorAll('[data-product-card]').forEach(card=>{const btn=card.querySelector('button');btn?.addEventListener('click',()=>{if(!dialog)return;dialogTitle.textContent=card.dataset.title||'Product details';dialogCopy.textContent=card.dataset.detail||card.dataset.note||'';if(dialogBest)dialogBest.textContent=card.dataset.best||'Ask LEE for the best pairing based on your planned dish.';if(dialogTip)dialogTip.textContent=card.dataset.tip||card.dataset.note||'';if(dialogStorage)dialogStorage.textContent=card.dataset.storage||'Check the product label and keep opened items sealed carefully.';dialog.showModal?dialog.showModal():dialog.setAttribute('open','')})});document.querySelector('[data-dialog-close]')?.addEventListener('click',()=>dialog?.close());
class ParticleField{constructor(canvas,{hero=false}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.hero=hero;this.particles=[];this.tick=0;this.resize();window.addEventListener('resize',()=>this.resize());this.animate()}resize(){const dpr=Math.min(window.devicePixelRatio||1,2);const rect=this.canvas.getBoundingClientRect();this.w=rect.width||window.innerWidth;this.h=rect.height||window.innerHeight;this.canvas.width=this.w*dpr;this.canvas.height=this.h*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);const area=(this.w*this.h)/12000;const count=this.hero?Math.max(360,Math.min(620,Math.round(area*4.4))):Math.max(220,Math.min(520,Math.round(area*2.8)));this.particles=Array.from({length:count},(_,i)=>this.makeParticle(i))}makeParticle(i){const angle=Math.random()*Math.PI*2;const radius=this.hero?70+Math.random()*270:Math.random()*Math.max(this.w,this.h);return{x:this.hero?this.w*.54+Math.cos(angle)*radius:Math.random()*this.w,y:this.hero?this.h*.48+Math.sin(angle)*radius*.55:Math.random()*this.h,vx:(Math.random()-.5)*.24,vy:(Math.random()-.5)*.24,r:this.hero?1+Math.random()*2.7:.8+Math.random()*2.2,a:.22+Math.random()*.68,phase:Math.random()*Math.PI*2,baseAngle:angle,baseRadius:radius}}animate(){if(reduce)return;this.tick+=.01;const c=this.ctx;c.clearRect(0,0,this.w,this.h);const rect=this.canvas.getBoundingClientRect();const mx=globalPointer.x-rect.left,my=globalPointer.y-rect.top;const active=globalPointer.active;const cx=this.hero?this.w*.54:this.w*.5;const cy=this.hero?this.h*.48:this.h*.45;for(const p of this.particles){if(this.hero){const wave=Math.sin(this.tick*1.35+p.phase)*20;const orbit=p.baseAngle+this.tick*.28;const targetX=cx+Math.cos(orbit)*(p.baseRadius+wave);const targetY=cy+Math.sin(orbit)*(p.baseRadius*.48+wave*.25);p.x+=(targetX-p.x)*.024;p.y+=(targetY-p.y)*.024}else{p.x+=p.vx+Math.sin(this.tick+p.phase)*.03;p.y+=p.vy+Math.cos(this.tick*.8+p.phase)*.03;if(p.x<-25)p.x=this.w+25;if(p.x>this.w+25)p.x=-25;if(p.y<-25)p.y=this.h+25;if(p.y>this.h+25)p.y=-25}if(active){const dx=mx-p.x,dy=my-p.y,dist=Math.hypot(dx,dy),range=this.hero?240:210;if(dist<range&&dist>1){const force=(1-dist/range)*(this.hero?1.18:.72);p.x+=dx/dist*force;p.y+=dy/dist*force}}c.beginPath();const glow=this.hero?0.95:0.62;c.fillStyle=`rgba(242,207,140,${p.a*glow})`;c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill()}requestAnimationFrame(()=>this.animate())}}
document.querySelectorAll('[data-particles]').forEach(canvas=>new ParticleField(canvas,{hero:canvas.dataset.particles==='hero'}));
