const header=document.querySelector('[data-header]');
const menuToggle=document.querySelector('[data-menu-toggle]');
const siteNav=document.querySelector('[data-site-nav]');
const reveals=document.querySelectorAll('.reveal');
const enterBtn=document.querySelector('[data-enter-site]');
const welcome=document.querySelector('[data-welcome]');
const reduce=window.matchMedia('(prefers-reduced-motion: reduce)').matches;

function setPointerVars(x,y){document.documentElement.style.setProperty('--mx',`${x}px`);document.documentElement.style.setProperty('--my',`${y}px`)}
setPointerVars(window.innerWidth*.5,window.innerHeight*.35);
window.addEventListener('pointermove',e=>setPointerVars(e.clientX,e.clientY),{passive:true});
menuToggle?.addEventListener('click',()=>{const open=siteNav?.classList.toggle('is-open');menuToggle.setAttribute('aria-expanded',String(Boolean(open)))});
if(enterBtn&&welcome){document.body.classList.add('no-scroll');enterBtn.addEventListener('click',()=>{welcome.classList.add('is-hidden');document.body.classList.remove('no-scroll')});}

const observer='IntersectionObserver'in window?new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in-view');observer.unobserve(entry.target)}})},{threshold:.1,rootMargin:'0px 0px -30px 0px'}):null;
reveals.forEach((el,i)=>{el.style.transitionDelay=`${Math.min(i*35,210)}ms`;observer?observer.observe(el):el.classList.add('in-view')});

document.querySelectorAll('[data-sound-control]').forEach(control=>{const audio=control.querySelector('[data-audio]');const btn=control.querySelector('[data-sound-toggle]');const label=control.querySelector('[data-sound-label]');if(!audio||!btn||!label)return;const sync=playing=>{btn.classList.toggle('is-playing',playing);btn.setAttribute('aria-pressed',String(playing));label.textContent=playing?'Pause':'Play me'};btn.addEventListener('click',async()=>{try{document.querySelectorAll('[data-audio]').forEach(a=>{if(a!==audio)a.pause()});document.querySelectorAll('[data-sound-toggle]').forEach(b=>{if(b!==btn)b.classList.remove('is-playing')});if(audio.paused){await audio.play();sync(true)}else{audio.pause();sync(false)}}catch(e){label.textContent='Tap again'}});audio.addEventListener('ended',()=>sync(false));audio.addEventListener('pause',()=>{if(!audio.ended)sync(false)})});

const locationPins=document.querySelectorAll('[data-location-pin]');const locationTitle=document.querySelector('[data-location-title]');const locationCopy=document.querySelector('[data-location-copy]');locationPins.forEach(pin=>pin.addEventListener('click',()=>{locationPins.forEach(p=>p.classList.remove('is-active'));pin.classList.add('is-active');if(locationTitle)locationTitle.textContent=pin.dataset.title||'Metro Manila';if(locationCopy)locationCopy.textContent=pin.dataset.copy||''}));locationPins[0]?.classList.add('is-active');

const dialog=document.querySelector('[data-product-dialog]');const dialogTitle=document.querySelector('[data-dialog-title]');const dialogCopy=document.querySelector('[data-dialog-copy]');const dialogKicker=document.querySelector('[data-dialog-kicker]');const dialogPair=document.querySelector('[data-dialog-pair]');const dialogTip=document.querySelector('[data-dialog-tip]');const dialogStorage=document.querySelector('[data-dialog-storage]');document.querySelectorAll('[data-product-card]').forEach(card=>{const btn=card.querySelector('button');btn?.addEventListener('click',()=>{if(!dialog)return;if(dialogKicker)dialogKicker.textContent=card.dataset.kicker||'Product details';if(dialogTitle)dialogTitle.textContent=card.dataset.title||'Product details';if(dialogCopy)dialogCopy.textContent=card.dataset.note||'';if(dialogPair)dialogPair.textContent=card.dataset.pair||'Message LEE for pairing guidance.';if(dialogTip)dialogTip.textContent=card.dataset.tip||'Use thoughtfully and taste as you go.';if(dialogStorage)dialogStorage.textContent=card.dataset.storage||'Check pack guidance and store carefully.';dialog.showModal?dialog.showModal():dialog.setAttribute('open','')})});document.querySelector('[data-dialog-close]')?.addEventListener('click',()=>dialog?.close());dialog?.addEventListener('click',event=>{const rect=dialog.getBoundingClientRect();const outside=event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom;if(outside)dialog.close()});

class ParticleField{constructor(canvas,{hero=false}={}){this.canvas=canvas;this.ctx=canvas.getContext('2d');this.hero=hero;this.mouse={x:0,y:0,active:false};this.particles=[];this.resize();window.addEventListener('resize',()=>this.resize());canvas.parentElement?.addEventListener('pointermove',e=>{const r=canvas.getBoundingClientRect();this.mouse.x=e.clientX-r.left;this.mouse.y=e.clientY-r.top;this.mouse.active=true},{passive:true});canvas.parentElement?.addEventListener('pointerleave',()=>this.mouse.active=false);if(!hero){window.addEventListener('pointermove',e=>{this.mouse.x=e.clientX;this.mouse.y=e.clientY;this.mouse.active=true},{passive:true})}this.tick=0;this.animate()}resize(){const dpr=Math.min(window.devicePixelRatio||1,2);const rect=this.canvas.getBoundingClientRect();this.w=rect.width||window.innerWidth;this.h=rect.height||window.innerHeight;this.canvas.width=this.w*dpr;this.canvas.height=this.h*dpr;this.ctx.setTransform(dpr,0,0,dpr,0,0);const count=this.hero?150:90;this.particles=Array.from({length:count},(_,i)=>this.makeParticle(i))}makeParticle(i){const angle=Math.random()*Math.PI*2;const radius=this.hero?80+Math.random()*210:Math.random()*Math.max(this.w,this.h);return{x:this.hero?this.w*.52+Math.cos(angle)*radius:Math.random()*this.w,y:this.hero?this.h*.46+Math.sin(angle)*radius:Math.random()*this.h,vx:(Math.random()-.5)*.22,vy:(Math.random()-.5)*.22,r:this.hero?1+Math.random()*2.4:.8+Math.random()*1.8,a:.25+Math.random()*.58,phase:Math.random()*Math.PI*2,baseAngle:angle,baseRadius:radius}}animate(){if(reduce)return;this.tick+=.01;const c=this.ctx;c.clearRect(0,0,this.w,this.h);const cx=this.hero?this.w*.52:this.w*.5;const cy=this.hero?this.h*.46:this.h*.45;for(const p of this.particles){if(this.hero){const breathe=Math.sin(this.tick*1.4+p.phase)*16;const targetX=cx+Math.cos(p.baseAngle+this.tick*.25)* (p.baseRadius+breathe);const targetY=cy+Math.sin(p.baseAngle+this.tick*.22)* (p.baseRadius*.45+breathe*.25);p.x+=(targetX-p.x)*.025;p.y+=(targetY-p.y)*.025}else{p.x+=p.vx;p.y+=p.vy;if(p.x<-20)p.x=this.w+20;if(p.x>this.w+20)p.x=-20;if(p.y<-20)p.y=this.h+20;if(p.y>this.h+20)p.y=-20}if(this.mouse.active){const dx=this.mouse.x-p.x,dy=this.mouse.y-p.y,dist=Math.hypot(dx,dy),range=this.hero?190:150;if(dist<range&&dist>1){const force=(1-dist/range)*(this.hero?.95:.36);p.x+=dx/dist*force;p.y+=dy/dist*force}}c.beginPath();c.fillStyle=`rgba(242,207,140,${p.a})`;c.arc(p.x,p.y,p.r,0,Math.PI*2);c.fill()}requestAnimationFrame(()=>this.animate())}}
document.querySelectorAll('[data-particles]').forEach(canvas=>new ParticleField(canvas,{hero:canvas.dataset.particles==='hero'}));
